server:
    port: 8080

spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: 2e38803268ab8115dbcd
                        client-secret: 2ae01326e5a373c9ae6b764132480c90d5b7736d