spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 2e38803268ab8115dbcd
            client-secret: 2ae01326e5a373c9ae6b764132480c90d5b7736d
#            accessTokenUri: https://github.com/login/oauth/access_token
#            userAuthorizationUri: https://github.com/login/oauth/authorize
#            client-name: Github user
#            provider: github
            scope: user:email
#            redirect-uri-template: http://localhost:8080/login/oauth2/code/github

server:
  port: 8080